apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-cabal-pod
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  volumes:
    - name: cabal
      configMap:
        name: {{ template "fullname" . }}-cabal-files

  containers:
    - name: helm-haskell-runtime
      image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
      command: ["sh", "-c", "printenv; cd /cabal; bash /cabal/create.sh"]
      volumeMounts:
        - mountPath: /cabal
          name: cabal
          readonly: true
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret }}
              key: db.user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret }}
              key: db.password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret }}
              key: db.host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secret }}
              key: db.port
  imagePullSecrets:
    - name: {{ .Values.secret.name }}
  restartPolicy: Never
