apiVersion: v1
data:
  db.host: {{ .Values.service.name | b64enc }}
  db.user: {{ .Values.secret.user | b64enc}}
  db.password: {{ .Values.secret.password | b64enc }}
  db.port: {{ .Values.service.externalPort | b64enc }}
  {{ if .Values.db.url }}
  db.url: {{ .Values.db.url | b64enc }}
  {{ end }}
  
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.secret.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
